modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/Brass-Goggled-Coders/Turtles/issues"
license = "MIT"

[[mods]]
modId = "turtles"
version = "${file.jarVersion}"
displayName = "Turtles"
authors = "SkySom"
description = '''
    '''

[[dependencies.turtles]]
modId = "forge"
mandatory = true
versionRange = "[40,41)"
ordering = "NONE"
side = "BOTH"
